// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Flyd = require("flyd");

describe("Flyd", (function () {
        Jest.test("#stream", (function (param) {
                return Jest.ExpectJs[/* toThrow */18](Jest.ExpectJs[/* not_ */23](Jest.ExpectJs[/* expect */0]((function (param) {
                                      return (function (param) {
                                          return Flyd.stream(4);
                                        });
                                    }))));
              }));
        Jest.test("#combine", (function (param) {
                return Jest.ExpectJs[/* toThrow */18](Jest.ExpectJs[/* not_ */23](Jest.ExpectJs[/* expect */0]((function (param) {
                                      return Flyd.combine((function (x) {
                                                    return x + 4 | 0;
                                                  }), /* array */[1]);
                                    }))));
              }));
        return Jest.test("#isStream", (function (param) {
                      return Jest.ExpectJs[/* toThrow */18](Jest.ExpectJs[/* not_ */23](Jest.ExpectJs[/* expect */0]((function (param) {
                                            return Flyd.isStream((function (param) {
                                                          return Flyd.stream(param);
                                                        }));
                                          }))));
                    }));
      }));

/*  Not a pure module */
