// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Flyd = require("flyd");

var Stream = /* module */[];

function make(value, param) {
  return Flyd.stream(value);
}

exports.Stream = Stream;
exports.make = make;
/* flyd Not a pure module */
